import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <>
        <ul className="py-4 px-20 flex">
          <li className="pr-8">
            <Link href={'/csr'} className="text-blue-600 underline">
            Client-side
            </Link>
          </li>
          <li className="pr-8">
            <Link href={'/ssr'} className="text-blue-600 underline">
            Server components
            </Link>
          </li>
          <li className="pr-8">
            <Link href={'/isr'} className="text-blue-600 underline">
            ISR
            </Link>
          </li>
        </ul>
        {children}
        </>
      
      </body>
    </html>
  );
}
